### ISSUE TITLE
Wrong screenshots

### ISSUE THREAD

**Issue by Huluti** [flathub/com.github.huluti.ImCompressor#1]
The app use wrong screenshots in Flathub website.
It use the ones from ImEditor if you check here: https://flathub.org/apps/details/com.github.huluti.ImCompressor
Here the good ones: https://github.com/Huluti/ImCompressor/tree/master/data/screenshots
Maybe a bug from flathub?
@nedrichards @barthalion

**Comment by bilelmoussaoui** [comment]
That's what you used on your appdata file https://github.com/Huluti/ImCompressor/blob/master/data/com.github.huluti.ImCompressor.appdata.xml.in#L24-L29

**Comment by Huluti** [comment]
Decidedly, only errors on my part. Really sorry.
