### ISSUE TITLE
ImCompressor have a new name

### ISSUE THREAD

**Issue by Huluti** [flathub/com.github.huluti.ImCompressor#3]
Hi! With ImCompressor being part of Gnome Circle now, we have a new icon and a new name. ImCompressor becomes **Curtail**.

Here's the new repo : https://github.com/Huluti/Curtail

When I will make a new release, how we'll can handle the transition ? Does the current users could be migrated to the new package?

Thank's for your answers!

**Comment by Huluti** [comment]
@barthalion @nedrichards @ebassi Sorry to bother you, but can someone help me with this task please?

**Comment by bilelmoussaoui** [comment]
If it's just a rename of the application, nothing has to be done? unless you have renamed the app-id as well, in such case, you have to re-submit your application with the new app-id, once it's merged you should End-Of-Life this one & redirect users to the new app-id, see https://github.com/flathub/flathub/wiki/App-Maintenance#end-of-life

**Comment by bilelmoussaoui** [comment]
Also, please tag `@flathub/reviewers` next time instead :)

**Comment by Huluti** [comment]
@bilelmoussaoui Thank you very much for your informations. I've also renamed the app-id so I'll go the second way!
